### ISSUE TITLE
digit problem in sobolcoeff.csv

### ISSUE THREAD

**Issue by cimatosa** [fazaghifari/SobolSampling#1]
Hi,

thanks for sharing your code. I have been looking for a python implementation of the Joe-Kuo program, and I found yours.

However, I noticed that for `d > 19350` your csv file is broken. It somehow does not allows for an `a` with more than 5 digits. For example the line

    19351,18,10002,5  1 3 1 1 29 43 11 105 331 693 1363 291 8191 7813 14135 38287 15469 256913

should be

    19351,18,100025,  1 3 1 1 29 43 11 105 331 693 1363 291 8191 7813 14135 38287 15469 256913

Cheers,
Richard

**Comment by fazaghifari** [comment]
Hi Richard,

Thank you very much for your feedback. I'll fix this problem
