### ISSUE TITLE
Function `sobol_points` cannot be loaded

### ISSUE THREAD

**Issue by a24hori** [fazaghifari/SobolSampling#2]
I have just been using your module `sobolsampling` but the Sobol sequence generator `sobol_points` cannot be load as you show in README.md.
Could you fix it?
```python
>>> import sobolsampling
>>> dir(sobolsampling)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
```

Thank you

**Comment by a24hori** [comment]
I found that it can be fixed by declaring `from sobolsampling import sobol_new` and then `sobol_new.sobol_points(num, dim)`.

**Comment by fazaghifari** [comment]
Thank you for your comments Keith! I'm sorry, I didn't write the import statement, I'll fix it as soon as I can
